### ISSUE TITLE
credentials

### ISSUE THREAD

**Issue by IzzySoft** [MaYiFei1995/PackageViewer#2]
I see you have the [full credentials in your `build.gradle`](https://github.com/MaYiFei1995/PackageViewer/blob/main/app/build.gradle#L16) and the keystore checked in as well. I don't think that's wise; your key must now be considered compromised. May I suggest you to change that (create a new key you do **not** check in here, remove the keystore and the credentials from the repo)? I'll meanwhile have to disable updates in the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid), blacklist that key and probably also to remove the app, as signing with that key cannot be considered safe.

**Comment by MaYiFei1995** [comment]
ignore

**Comment by IzzySoft** [comment]
Ignore? That leaves me no choice but to remove your app from IzzyOnDroid then, for security reasons, sorry. Be welcome to give me a ping should you've changed your mind and want it back in the listing.
